### ISSUE TITLE
The checkpoints may be mistaken.

### ISSUE THREAD

**Issue by LemonQC** [Kamalnl92/Self-Supervised-Learning-for-pushing-and-grasping#1]
Code : python main.py --stage push_grasp --num_obj 10 --experience_replay --explore_rate_decay --is_testing --test_preset_cases --test_preset_file 'simulation/test-cases/test-10-obj-06.txt' --load_snapshot --snapshot_file JointPushGraspModelNoMaskInput.pth --save_visualizations --grasp_goal_conditioned --goal_conditioned --goal_obj_idx 1 > test1.txt

It got errors:
![image](https://github.com/Kamalnl92/Self-Supervised-Learning-for-pushing-and-grasping/assets/30914380/db03fe2a-7ec6-4536-b565-b5c968e52392)

**Comment by Kamalnl92** [comment]
I have uploaded a new model JointPushGraspModelNoMaskInput_b.pth, could you try it.
