### ISSUE TITLE
About the test question

### ISSUE THREAD

**Issue by hanyueling** [Kamalnl92/Self-Supervised-Learning-for-pushing-and-grasping#3]
I'm having trouble trying to reproduce this paper. When I downloaded the pre-trained model. Then testing on test1. The terminal will report an error showing that there is no value for depth.
python main.py --stage push_grasp --num_obj 10 --experience_replay --explore_rate_decay --is_testing --test_preset_cases --test_preset_file 'simulation/test-cases/test-10-obj-06.txt' --load_snapshot --snapshot_file 'JointPushGraspModelMaskInput.pth' --save_visualizations --grasp_goal_conditioned --goal_conditioned --goal_obj_idx 1 > test1.txt
Traceback (most recent call last):
  File "main.py", line 810, in <module>
    main(args)
  File "main.py", line 75, in main
    robot = Robot(stage, goal_object, obj_mesh_dir, num_obj, workspace_limits,
  File "/home/lhy/Self-Supervised-Learning-for-pushing-and-grasping/robot.py", line 82, in __init__
    self.setup_sim_camera()
  File "/home/lhy/Self-Supervised-Learning-for-pushing-and-grasping/robot.py", line 123, in setup_sim_camera
    self.bg_color_img, self.bg_depth_img = self.get_camera_data()
  File "/home/lhy/Self-Supervised-Learning-for-pushing-and-grasping/robot.py", line 380, in get_camera_data
    return color_img, depth_img
UnboundLocalError: local variable 'depth_img' referenced before assignment

**Comment by wyl1253** [comment]
Hi Yueling,

I understand you're having trouble getting the depth image from the camera in CoppeliaSim. Based on your problem, here are a few steps to troubleshoot and improve the process:

1. Extend the Duration: In the `robot.py` file, increase the duration or timeout for the "def get_camera_data(self):" function. This often helps when the simulator is slower to respond, especially when interacting with cameras.

2. Check Environment Reset: Make sure that the environment is being successfully reset after each interaction or run. Sometimes, if the environment isn’t reset properly, it could cause issues in retrieving images.

3. Test RGB Image: If you can successfully obtain the RGB image, theoretically, you should be able to get the depth image as well. Ensure you can capture RGB images first to confirm that the camera is working correctly.

If you’ve already successfully tested one of the scenes on your end, and it can retrieve depth data, this should be a configuration issue. Let me know how it goes! Good luck!

Best Regards,  
Yongliang
